name: Xcode con Theos

on:
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Theos Environment
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS16.5.sdk.tar.xz
        tar -xf iPhoneOS16.5.sdk.tar.xz -C $HOME/theos/sdks/
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Initialize Theos SPM Configuration
      run: |
        export THEOS=$HOME/theos
        make spm

    - name: Run Xcodebuild List
      run: |
        export THEOS=$HOME/theos
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        echo "Schemes: $scheme_list"
        
        # Compilación del paquete final usando el Makefile
        make package FINALPACKAGE=1

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EeveeSpotifyBuild
        path: packages/
